language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lewismclennan/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true lewismclennan/docker-react npm run test